apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/frontend

namePrefix: dev-
namespace: dev

labels:
  - pairs:
      env: development
    includeSelectors: true

replicas:
  - name: frontend
    count: 1

configMapGenerator:
- name: frontend-config
  behavior: merge
  files:
    - default.conf.template=default.conf.template
  literals:
    - VITE_API_BASE_URL=http://dev-backend-service:5500
    # Add the variable your Nginx template uses, for example:
    - BACKEND_HOST=dev-backend-service

patches:
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "125Mi"
          cpu: "100m"
        limits:
          memory: "250Mi"
          cpu: "150m"

