apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dev126712/express-api:8eddf3fa95abbae87bc450ab04a509aae04009c8
        imagePullPolicy: true
        ports:
        - containerPort: 5500
        envFrom:
          - configMapRef:
              name: backend-config
        env:
          - name: DB_URI
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: DB_URI
          - name: ARCJET_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: ARCJET_KEY
          - name: QSTASH_TOKEN
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: QSTASH_TOKEN 
        resources: 
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe: 
          httpGet:
            path: /healthz
            port: 5500
          initialDelaySeconds: 15
          timeoutSeconds: 5       
          failureThreshold: 3
          periodSeconds: 20
        readinessProbe: 
          httpGet:
            path: /readyz
            port: 5500
          initialDelaySeconds: 20  
          timeoutSeconds: 10       
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: backend-logs
            mountPath: /app/logs

      volumes:
        - name: backend-logs
          emptyDir: {} # Temporary storage for logs, cleared on pod restart
