apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  ARCJET_ENV: "development"
  QSTASH_URL: "https://qstash.upstash.io"
  QSTASH_TOKEN: "eyJVc2VySUQiOiJkZWZhdWx0VXNlciIsIlBhc3N3b3JkIjoiZGVmYXVsdFBhc3N3b3JkIn0="
  ALLOWED_ORIGINS: "https://ca3fdb5fee7c-10-244-7-197-31220.saci.r.killercoda.com,http://localhost:5173"
  JWT_SECRET: "secret123"
  JWT_EXPIRES_IN: "3d"
  ARCJET_KEY: "ajkey_01k6jyd7w6f61r7y5ycg4r09jk"
  ARCJET_ENV: "development"
