apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  ARCJET_ENV: "development"
  QSTASH_URL: "https://qstash.upstash.io"
  ALLOWED_ORIGINS: "https://ca3fdb5fee7c-10-244-7-197-31220.saci.r.killercoda.com,http://localhost:5173"

