apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yml
  - backend-serivice.yml    # Match your exact spelling in the repo
  - backend-configmap.yml
  - backend-secrets.yml
  - backend-hpa.yml
