apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deploymeny.yml  # Match your exact spelling in the repo
  - frontend-service.yml
  - frontend-configmap.yml
  - frontend-hpa.yml
