name: K8s security scan
on:
  push: 
    branches: [ main ]

jobs:
  security-scan-manifest-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy (Table output for console)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          # Scanning the root ensures all bases and overlays are checked
          scan-ref: '.'
          format: 'table'
          # '0' ensures the pipeline keeps going so you can deploy
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} 
